#!/bin/bash
###############################################################################
#
# A script for send Nagios Notification to HipChat
#
# Inspired by: http://github.com/hipchat/hipchat-cli
#
###############################################################################

# exit on failure
set -e

# Configuration
HOST="XXXX.hipchat.com"
TOKEN="XXXX"
ROOM_ID=XXXX


# nagios levels
if [ ! -z "$1" ]; then
LEVEL=$1
if [ ! -z "$LEVEL" ]; then
  if [[ $LEVEL == 'CRITICAL' ]] || [[ $LEVEL == 'critical' ]]; then
    COLOR="red";
  elif [[ $LEVEL == 'WARNING' ]] || [[ $LEVEL == 'warning' ]]; then
    COLOR="yellow";
  elif [[ $LEVEL == 'UNKNOWN' ]] || [[ $LEVEL == 'unknown' ]]; then
    COLOR="gray";
  elif [[ $LEVEL == 'OK' ]] || [[ $LEVEL == 'ok' ]]; then
    COLOR="green";
  elif [[ $LEVEL == 'DOWN' ]] || [[ $LEVEL == 'down' ]]; then
    COLOR="red";
  elif [[ $LEVEL == 'UP' ]] || [[ $LEVEL == 'up' ]]; then
    COLOR="green";
  fi
fi
else
/bin/echo "Please send a Nagios Level. Usage: $0 <NAGIOS_LEVEL> <TYPE>"
exit 1
fi

# From (Host or Service)
if [ ! -z "$2" ]; then
	TYPE=$2
else
	TYPE=""
fi

if [ -z "$INPUT" ]; then
  # read stdin
  INPUT=$(cat)
fi

# replace newlines with XHTML <br>
INPUT=$(echo -n "${INPUT}" | sed "s/$/\<br\>/")

# replace bare URLs with real hyperlinks
INPUT=$(echo -n "${INPUT}" | perl -p -e "s/(?<!href=\"|href=')((?:https?|ftp|mailto)\:\/\/[^ \n]*)/\<a href=\"\1\"\>\1\<\/a>/g")

# do the curl
curl -sS \
	-H 'Content-type: application/json' \
	-d "{\"color\":\"$COLOR\", \"message\":\"$INPUT\", \"message_format\":\"html\", \"notify\":true, \"from\":\"$TYPE\"}" \
	https://$HOST/v2/room/$ROOM_ID/notification?auth_token=$TOKEN